from django.core.exceptions import ValidationError

def validate_load_start_data(request):
    # raise ValidationError({"test": "test_test"})
    return True